= MINGW-packages for Electronic Design Automation (EDA)
:toc: left
:toclevels: 4
:repotree: https://github.com/hdl/MINGW-packages/tree/main/
:toc-title: MINGW-packages for EDA
:icons: font
:docinfo: shared

[.text-center]
https://github.com/hdl/MINGW-packages[image:https://img.shields.io/badge/hdl-MINGW--packages-f2f1ef.svg?longCache=true&style=flat-square&logo=GitHub&logoColor=f2f1ef[title='hdl/MINGW-packages GitHub repository']]
https://github.com/hdl/packages[image:https://img.shields.io/badge/hdl-packages-f2f1ef.svg?longCache=true&style=flat-square&logo=GitHub&logoColor=f2f1ef[title='hdl/packages GitHub repository']] |
https://gitter.im/hdl/community[image:https://img.shields.io/gitter/room/hdl/community.svg?longCache=true&style=flat-square&logo=gitter&logoColor=fff&color=4db797[title='hdl/community on gitter.im']] |
https://github.com/hdl/awesome[image:https://img.shields.io/badge/hdl-awesome-f2f1ef.svg?longCache=true&style=flat-square&logo=GitHub&logoColor=f2f1ef[title='hdl/awesome GitHub repository']]
https://github.com/hdl/constraints[image:https://img.shields.io/badge/hdl-constraints-f2f1ef.svg?longCache=true&style=flat-square&logo=GitHub&logoColor=f2f1ef[title='hdl/constraints GitHub repository']]
https://github.com/hdl/smoke-tests[image:https://img.shields.io/badge/hdl-smoke--tests-f2f1ef.svg?longCache=true&style=flat-square&logo=GitHub&logoColor=f2f1ef[title='hdl/smoke-tests GitHub repository']]

This repository contains references to package recipes (PKGBUILD files) for https://en.wikipedia.org/wiki/Electronic_design_automation[electronic design automation (EDA)] tools/projects to be built as MinGW-w64 targets on https://www.msys2.org/[MSYS2] (MINGW32 and MINGW64). The main purpose is coordination of contributions for upstreaming all tools/projects to official MSYS2 repositories, and having them updated periodically. See <<Context>> for a discussion about other packaging alternatives for EDA tooling.

== Context

Multiple open source and/or free EDA tools are developed and primarily used on GNU/Linux platforms. Typically, builds are managed with tools such as `make` or `cmake`, and GCC or LLVM/Clang are used for compiling. Migrating all those build systems to _native_ Windows toolchains can be painful. Using PKGBUILD files for MINGW32/MINGW64 allows reusing the existing plumbing and, at the same time, produced binaries can be used on Windows natively. MSYS2 is the most used environment for building open source EDA tools already; however, most projects don't use PKGBUILD recipes but custom scripts. Hence, the work on this project is mainly rewriting custom scripts for adhering to MSYS2 packaging guidelines.

Overall, there are a handful of approaches for providing _great prepackaged/prebuilt and easy-to-set-up EDA tooling environments_: see https://github.com/hdl/smoke-tests/blob/main/CONTEXT.md[hdl/smoke-tests: CONTEXT].

include::tools.adoc[]

include::usage.adoc[]

include::contributing.adoc[]
